const coverLetterTemplates = {
  ats: [
    { id: 1, key: "ats/ats1", image: "/templates/ats/ats1.png" },
    { id: 2, key: "ats/ats2", image: "/templates/ats/ats2.png" },
    { id: 3, key: "ats/ats3", image: "/templates/ats/ats3.png" },
    { id: 4, key: "ats/ats4", image: "/templates/ats/ats4.png" },
    { id: 5, key: "ats/ats5", image: "/templates/ats/ats5.png" },
    { id: 6, key: "ats/ats6", image: "/templates/ats/ats6.png" },
    { id: 7, key: "ats/ats7", image: "/templates/ats/ats7.png" },
    { id: 8, key: "ats/ats8", image: "/templates/ats/ats8.png" },
    { id: 9, key: "ats/ats9", image: "/templates/ats/ats9.png" },
    { id: 10, key: "ats/ats10", image: "/templates/ats/ats10.png" },
  ],
  creative: [
    { id: 11, key: "creative/creative1", image: "/templates/creative/creative1.png" },
    { id: 12, key: "creative/creative2", image: "/templates/creative/creative2.png" },
    { id: 13, key: "creative/creative3", image: "/templates/creative/creative3.png" },
    { id: 14, key: "creative/creative4", image: "/templates/creative/creative4.png" },
    { id: 15, key: "creative/creative5", image: "/templates/creative/creative5.png" },
    { id: 16, key: "creative/creative6", image: "/templates/creative/creative6.png" },
    { id: 17, key: "creative/creative7", image: "/templates/creative/creative7.png" },
    { id: 18, key: "creative/creative8", image: "/templates/creative/creative8.png" },
    { id: 19, key: "creative/creative9", image: "/templates/creative/creative9.png" },
    { id: 20, key: "creative/creative10", image: "/templates/creative/creative10.png" },
  ],
  europass: [
    { id: 21, key: "europass/europass1", image: "/templates/europass/europass1.png" },
    { id: 22, key: "europass/europass2", image: "/templates/europass/europass2.png" },
    { id: 23, key: "europass/europass3", image: "/templates/europass/europass3.png" },
    { id: 24, key: "europass/europass4", image: "/templates/europass/europass4.png" },
    { id: 25, key: "europass/europass5", image: "/templates/europass/europass5.png" },
    { id: 26, key: "europass/europass6", image: "/templates/europass/europass6.png" },
    { id: 27, key: "europass/europass7", image: "/templates/europass/europass7.png" },
    { id: 28, key: "europass/europass8", image: "/templates/europass/europass8.png" },
    { id: 29, key: "europass/europass9", image: "/templates/europass/europass9.png" },
    { id: 30, key: "europass/europass10", image: "/templates/europass/europass10.png" },
  ],
  modern: [
    { id: 31, key: "modern/modern1", image: "/templates/modern/modern1.png" },
    { id: 32, key: "modern/modern2", image: "/templates/modern/modern2.png" },
    { id: 33, key: "modern/modern3", image: "/templates/modern/modern3.png" },
    { id: 34, key: "modern/modern4", image: "/templates/modern/modern4.png" },
    { id: 35, key: "modern/modern5", image: "/templates/modern/modern5.png" },
    { id: 36, key: "modern/modern6", image: "/templates/modern/modern6.png" },
    { id: 37, key: "modern/modern7", image: "/templates/modern/modern7.png" },
    { id: 38, key: "modern/modern8", image: "/templates/modern/modern8.png" },
    { id: 39, key: "modern/modern9", image: "/templates/modern/modern9.png" },
    { id: 40, key: "modern/modern10", image: "/templates/modern/modern10.png" },
  ],
  professional: [
    { id: 41, key: "professional/professional1", image: "/templates/professional/professional1.png" },
    { id: 42, key: "professional/professional2", image: "/templates/professional/professional2.png" },
    { id: 43, key: "professional/professional3", image: "/templates/professional/professional3.png" },
    { id: 44, key: "professional/professional4", image: "/templates/professional/professional4.png" },
    { id: 45, key: "professional/professional5", image: "/templates/professional/professional5.png" },
    { id: 46, key: "professional/professional6", image: "/templates/professional/professional6.png" },
    { id: 47, key: "professional/professional7", image: "/templates/professional/professional7.png" },
    { id: 48, key: "professional/professional8", image: "/templates/professional/professional8.png" },
    { id: 49, key: "professional/professional9", image: "/templates/professional/professional9.png" },
    { id: 50, key: "professional/professional10", image: "/templates/professional/professional10.png" },
  ],
};

export default coverLetterTemplates;
